// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUXT03ytd6HWy78ZcDDYvXuDLNHevDDi4',
    appId: '1:202737392623:web:6f9fd59cc8e947ef30341a',
    messagingSenderId: '202737392623',
    projectId: 'dellsparkcity',
    authDomain: 'dellsparkcity.firebaseapp.com',
    storageBucket: 'dellsparkcity.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmuOzbtOx2Yz5ZQLE5dgOEg-yhp0ed1_Q',
    appId: '1:202737392623:android:e8216596ff6d817a30341a',
    messagingSenderId: '202737392623',
    projectId: 'dellsparkcity',
    storageBucket: 'dellsparkcity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvGaCilL8WZwbnRrbZa1UmqhXSK80Ki_0',
    appId: '1:202737392623:ios:f478e9b564bd88bb30341a',
    messagingSenderId: '202737392623',
    projectId: 'dellsparkcity',
    storageBucket: 'dellsparkcity.appspot.com',
    iosBundleId: 'com.example.dellsparkcity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvGaCilL8WZwbnRrbZa1UmqhXSK80Ki_0',
    appId: '1:202737392623:ios:0ab0792f4e3b409f30341a',
    messagingSenderId: '202737392623',
    projectId: 'dellsparkcity',
    storageBucket: 'dellsparkcity.appspot.com',
    iosBundleId: 'com.example.dellsparkcity.RunnerTests',
  );
}
